"""empty message

Revision ID: e6be820560b5
Revises: 51bb4eafa23d
Create Date: 2021-09-10 20:44:49.118287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6be820560b5'
down_revision = '51bb4eafa23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('create')
    op.drop_table('join')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='join_community_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='join_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='join_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='join_pkey')
    )
    op.create_table('create',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='create_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='create_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='create_pkey')
    )
    op.drop_table('membership')
    # ### end Alembic commands ###
